### ISSUE TITLE
Weapons remain after death on prisoner

### ISSUE THREAD

**Issue by Jabbers99** [kurt-stolle/jailbreak#16]
If you die with a gun out whilst a prisoner, when spectating the gun viewmodel will remain whilst spectating.
Using x64 branch

![](https://i.imgur.com/P7bgJLz.jpg)

**Comment by khwstolle** [comment]
This bug did not exist when I published this project. It is thus the result of some Garry's Mod patch, which means the fix is somewhere in the patch notes. 

Sadly, I am unable to maintain this project myself. Please make a PR if you manage to fix it yourself.
