### ISSUE TITLE
Player weapons / gear bugging away

### ISSUE THREAD

**Issue by SanNick** [kurt-stolle/jailbreak#2]
Hi, 

can you please fix that the gear / the weapons dont´t bugging away from the players while they moving.

Your sincerly
SanNick

 Here´s a picture: ![jb_military_jail_beta10004](https://cloud.githubusercontent.com/assets/17143698/12919586/1625d192-cf45-11e5-94b1-8775aa7eb023.jpg)

**Comment by khwstolle** [comment]
Cannot recreate the issue
