### ISSUE TITLE
Players flash out after joining the server

### ISSUE THREAD

**Issue by takaqiao** [kurt-stolle/jailbreak#4]
When players kills a player players will flash out

**Comment by TNovalis** [comment]
Most likely due to something other than Jailbreak. Try and see if you the same results with just Jailbreak on your server.

**Comment by takaqiao** [comment]
Ok..

**Comment by TNovalis** [comment]
The way I recommend to install addons is 1-3 at a time to make sure everything works properly, that way you can track down conflicts and problems easier.

**Comment by takaqiao** [comment]
i think its language problem
players with chinese names will flash outt

**Comment by TNovalis** [comment]
So you can confirm this happens with **only** jailbreak? If so have you checked console for any errors, also please provide screenshots.

**Comment by takaqiao** [comment]
yep but no errors..
XXX timed out

**Comment by takaqiao** [comment]
@kurt-stolle

**Comment by khwstolle** [comment]
First of all, I don't think there is a way JB will conflict with other addons. I have written it in a way that makes such conflicts nearly impossible.

Could you maybe make screenshots or videos of what the issue is. I find it hard to pinpoint what you mean exactly just from the comments you made on the issue.

**Comment by takaqiao** [comment]
I dont know what should i make screenshots(Bcuz no any errors)
If players use foreign name to join the server.When a round finished,Client will crash(All players)

**Comment by takaqiao** [comment]
@kurt-stolle

**Comment by takaqiao** [comment]
Btw sry for my poor English

**Comment by TNovalis** [comment]
Record the incident and post the link here.

**Comment by takaqiao** [comment]
[JB DEBUG] [SERVER] [08/14/16 21:43:10]         Received config request by: å°è
Œ—åŒå­¦
Dropped å°èŒ—åŒå­¦ from server (å°èŒ—åŒå­¦ timed out)
Client "å°èŒ—åŒå­¦" connected (121.13.144.20:7834).
[JB DEBUG] [SERVER] [08/14/16 21:44:54]         å°èŒ—åŒå­¦ has successfully jo
ined the server.

**Comment by takaqiao** [comment]
I cant capture the server crash...

**Comment by takaqiao** [comment]
sry client crash

**Comment by khwstolle** [comment]
Issue cannot be recreated
